/*
 * @Author: Leniakea
 * @Date: 2022-10-28 09:40:11
 * @LastEditors: Leniakea
 * @LastEditTime: 2022-10-31 13:28:41
 * @FilePath: \webpage\src\TagColor.tsx
 */
export default {
  历史: 'purple',
  爱情: 'magenta',
  青春: 'volcano',
  女性: 'magenta',
  情色: 'orange',
  浪漫: 'volcano',
  唯美: 'blue',
  剧情: 'geekblue',
  喜剧: 'volcano',
  悬疑: 'geekblue',
  经典: 'blue',
  动画: 'green',
  科幻: 'geekblue',
  犯罪: 'red',
  动作: 'geekblue',
  搞笑: 'orange',
  文艺: 'cyan',
  惊悚: 'purole',
  励志: 'red',
  纪录片: 'blue',
  黑色幽默: 'purple',
  战争: 'red',
  家庭: 'lime',
  恐怖: 'purple',
  感人: 'red',
  魔幻: 'orange',
  传记: 'cyan',
  短片: 'lime',
  音乐: 'volcano',
  暴力: 'red',
  童年: 'gold',
  黑帮: 'purple',
  烂片: 'lime',
  史诗: 'blue',
  动画短片: 'green',
  童话: 'gold',
  同志: 'green',
  震撼: 'red',
  西部: 'gold',
  种族: 'lime',
  功夫: 'red',
  cult: 'purple',
  孤独: 'geekblue',
  新浪潮: 'magenta',
  独立: 'red',
};
